# ===================================================================
# Namespace for all Grafana training environments
# ===================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: grafana-training

---
# ===================================================================
# Shared Secret for Grafana Admin Password
# ===================================================================
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: grafana-training
stringData:
  # This environment variable sets the admin password for all Grafana instances
  GF_SECURITY_ADMIN_PASSWORD: "grafana"

---
# ===================================================================
# Grafana Instance 1
# ===================================================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc-1
  namespace: grafana-training
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi # Adjust storage size as needed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment-1
  namespace: grafana-training
spec:
  # This line ensures that only one pod (replica) will ever be running for this deployment.
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: grafana-1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/instance: grafana-1
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:11.1.0 # Use a specific, recent version
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - secretRef:
                name: grafana-admin-secret
          # --- MODIFIED SECTION ---
          # Increased delays to give Grafana more time to start up before probes begin.
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 45 # Increased from 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 60 # Increased from 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc-1
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service-1
  namespace: grafana-training
spec:
  selector:
    app.kubernetes.io/instance: grafana-1
  # Corrected section: The 'ports' block was duplicated. This is the correct syntax.
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

